### ISSUE TITLE
Remove Flux plugin links

### ISSUE THREAD

**Issue by dougstjohn** [flipboxfactory/flux#1]
There are a handful of links to the Flux plugin that need removed. 

- Remove Craft admin sidebar item

- Remove cogwheel from /admin/settings/plugins

- Remove /admin/settings page

**Comment by nateiler** [comment]
I'm pretty sure these are all taken care of in the next release (they're in develop right now).

**Comment by dougstjohn** [comment]
Completed. Closing.
